<x-app-layout>
    <x-slot name="header"><h2 class="text-2xl font-semibold text-slate-900">Tetapan Admin</h2></x-slot>
    <div class="py-8"><div class="mx-auto max-w-6xl space-y-6 px-4 sm:px-6 lg:px-8">
        @if (session('status'))<div class="rounded-lg border border-teal-200 bg-teal-50 px-4 py-3 text-sm text-teal-800">{{ session('status') }}</div>@endif
        @if ($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
        <div class="rounded-lg border border-red-200 bg-white p-6 shadow-sm"><h3 class="text-lg font-semibold text-red-800">Reset rekod resit</h3><p class="mt-2 text-sm text-slate-600">Tindakan ini memadam semua rekod resit. Rekod bayaran tidak dipadam. Nombor resit tahun semasa akan bermula semula dari 000001.</p><form method="POST" action="{{ route('admin.settings.reset-receipts') }}" class="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end">@csrf<label class="text-sm font-medium text-slate-700">Taip <span class="font-bold">PADAM RESIT</span> untuk sahkan<input name="confirmation" class="mt-1 block w-full rounded-lg border-slate-300 sm:w-64" required></label><button class="rounded-lg bg-red-600 px-4 py-2 font-semibold text-white hover:bg-red-700" onclick="return confirm('Tindakan ini akan memadam semua resit. Teruskan?')">Padam semua resit</button></form></div>
        <div class="rounded-lg border border-red-300 bg-red-50 p-6 shadow-sm"><h3 class="text-lg font-semibold text-red-900">Padam semua rekod bayaran dan resit</h3><p class="mt-2 text-sm text-red-800">Tindakan paling berat: semua rekod bayaran, peruntukan bayaran, tuntutan item dan resit akan dipadam. Data sekolah, keluarga, pelajar dan item yuran tidak terjejas.</p><form method="POST" action="{{ route('admin.settings.reset-payments-and-receipts') }}" class="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end">@csrf<label class="text-sm font-medium text-red-900">Taip <span class="font-bold">PADAM SEMUA BAYARAN</span> untuk sahkan<input name="confirmation" class="mt-1 block w-full rounded-lg border-red-300 bg-white sm:w-72" required></label><button type="submit" class="rounded-lg bg-red-600 px-4 py-2 font-semibold text-white hover:bg-red-700" style="background-color:#dc2626;color:#ffffff" onclick="return confirm('AMARAN: Semua rekod bayaran dan resit akan dipadam dan tidak boleh dipulihkan. Teruskan?')">Padam semua bayaran &amp; resit</button></form></div>
        <div class="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><h3 class="text-lg font-semibold text-slate-900">Pengguna sistem</h3><div class="mt-4 overflow-x-auto rounded-lg border border-slate-200"><table class="w-full min-w-[680px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr class="border-b border-slate-200"><th class="px-5 py-3 font-semibold">Nama</th><th class="px-5 py-3 font-semibold">Email</th><th class="px-5 py-3 font-semibold">Peranan</th><th class="px-5 py-3 text-right font-semibold">Tindakan</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($users as $user)<tr class="transition-colors hover:bg-slate-50"><td class="whitespace-nowrap px-5 py-4 font-medium text-slate-800">{{ $user->name }}</td><td class="whitespace-nowrap px-5 py-4 text-slate-600">{{ $user->email }}</td><td class="px-5 py-4"><span class="inline-flex rounded-full bg-teal-50 px-3 py-1 text-xs font-semibold text-teal-700">{{ $user->roles->pluck('role')->join(', ') ?: '-' }}</span></td><td class="px-5 py-4 text-right">@if (! $user->is(auth()->user()))<form method="POST" action="{{ route('admin.settings.users.destroy', $user) }}" onsubmit="return confirm('Padam pengguna ini? Tindakan ini tidak boleh dipulihkan.')" class="inline">@csrf @method('DELETE')<button class="rounded-lg bg-red-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-red-700">Padam</button></form>@else<span class="text-xs font-medium text-slate-400">Akaun semasa</span>@endif</td></tr>@empty<tr><td colspan="4" class="px-5 py-8 text-center text-slate-500">Tiada pengguna.</td></tr>@endforelse</tbody></table></div></div>
    </div></div>
</x-app-layout>
