<x-app-layout>
    <x-slot name="header"><h2 class="text-2xl font-semibold text-slate-900">Buat bayaran</h2></x-slot>
    <div class="py-8"><div class="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8"><div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <p class="text-sm text-slate-500">Pilih item sumbangan untuk setiap anak. Item yang telah dibayar kekal dipaparkan sebagai rujukan.</p>
        <form method="POST" action="{{ route('payments.store') }}" class="mt-6 space-y-5">@csrf
            <input type="hidden" name="school_id" id="school_id">
            <div><label class="block text-sm font-medium">Keluarga</label><select name="family_id" id="family_id" class="mt-1 w-full rounded-lg border-slate-300" required><option value="">Pilih keluarga</option>@foreach($families as $family)<option value="{{ $family->id }}" data-school="{{ $family->school_id }}">{{ $family->name }} — {{ $family->school?->name }}</option>@endforeach</select></div>
            <div id="student-items" class="space-y-4">@foreach($families as $family)<div data-family="{{ $family->id }}" class="hidden space-y-4">@forelse($family->students as $student)<div class="rounded-xl border border-slate-200 p-4"><div class="font-semibold text-slate-900">{{ $student->full_name }}</div><div class="mt-3 divide-y divide-slate-100">@forelse($student->charges->where('balance_amount','>',0) as $charge)@php($paid = in_array($charge->id, $claimedItemIds ?? [], true))<label class="flex items-center justify-between gap-3 py-3 text-sm {{ $paid ? 'text-slate-400' : 'text-slate-700' }}"><span class="flex items-center gap-3"><input type="checkbox" name="student_fee_charge_ids[]" value="{{ $charge->id }}" data-amount="{{ $paid ? '0.00' : $charge->balance_amount }}" class="student-charge rounded border-slate-300 text-teal-700" {{ $paid ? 'checked disabled' : '' }}><span>{{ $charge->feeCategory?->name ?: 'Sumbangan PIBG' }}@if($paid) <span class="ml-1 text-xs font-medium text-slate-400">(Sudah dijelaskan)</span>@endif</span></span><span class="font-semibold">RM {{ $paid ? '0.00' : number_format($charge->balance_amount,2) }}</span></label>@empty<p class="py-3 text-sm text-slate-500">Tiada item tertunggak.</p>@endforelse</div></div>@empty<p class="rounded-lg bg-amber-50 p-4 text-sm text-amber-800">Tiada anak dipautkan kepada keluarga ini.</p>@endforelse</div>@endforeach</div>
            <div class="rounded-xl bg-slate-50 p-4"><div class="flex justify-between"><span class="text-sm text-slate-500">Jumlah dipilih</span><span id="total" class="text-2xl font-bold text-teal-700">RM 0.00</span></div><input name="amount" id="amount" type="hidden" value="0"></div>
            <input type="hidden" name="method" value="DIRECT_FPX_DUITNOW"><p class="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">Gerbang Direct FPX / DuitNow akan dibuka selepas pengesahan. Mod semasa ialah UAT sehingga pihak bank memberikan Merchant ID dan kunci API rasmi.</p><button class="w-full rounded-lg bg-teal-700 px-5 py-3 font-semibold text-white hover:bg-teal-800">Teruskan ke bayaran</button>
        </form>
    </div></div></div>
    <script>const family=document.getElementById('family_id'),school=document.getElementById('school_id'),total=document.getElementById('total'),amount=document.getElementById('amount');function refresh(){let sum=0;document.querySelectorAll('.student-charge:checked:not(:disabled)').forEach(c=>sum+=Number(c.dataset.amount||0));total.textContent='RM '+sum.toFixed(2);amount.value=sum.toFixed(2);}family?.addEventListener('change',()=>{school.value=family.options[family.selectedIndex]?.dataset.school||'';document.querySelectorAll('[data-family]').forEach(x=>x.classList.toggle('hidden',x.dataset.family!==family.value));document.querySelectorAll('.student-charge:not(:disabled)').forEach(x=>x.checked=false);refresh();});document.addEventListener('change',e=>{if(e.target.classList.contains('student-charge'))refresh();});</script>
</x-app-layout>
