<x-app-layout>
    <x-slot name="header"><h2 class="text-2xl font-semibold text-slate-900">Resit Bayaran</h2></x-slot>
    <div class="py-8"><div class="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
        <div class="page-card overflow-hidden">
            <div class="border-b border-slate-200 bg-teal-800 px-6 py-6 text-white sm:px-8"><div class="text-sm uppercase tracking-widest text-teal-100">Platform Pengurusan PIBG</div><div class="mt-3 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h3 class="text-2xl font-bold">Resit Rasmi</h3><p class="mt-1 text-teal-100">{{ $payment->receipt?->receipt_number }}</p></div><span class="rounded-full bg-white/15 px-3 py-1 text-sm font-semibold">{{ $payment->receipt?->status ?? $payment->status }}</span></div></div>
            <div class="space-y-6 p-6 sm:p-8"><div class="grid gap-5 sm:grid-cols-2"><div><div class="text-xs uppercase tracking-wide text-slate-500">Sekolah</div><div class="mt-1 font-semibold">{{ $payment->school?->name }}</div></div><div><div class="text-xs uppercase tracking-wide text-slate-500">Tarikh bayaran</div><div class="mt-1 font-semibold">{{ $payment->paid_at?->format('d/m/Y H:i') ?? '-' }}</div></div><div><div class="text-xs uppercase tracking-wide text-slate-500">Keluarga</div><div class="mt-1 font-semibold">{{ $payment->family?->name }}</div></div><div><div class="text-xs uppercase tracking-wide text-slate-500">Kaedah bayaran</div><div class="mt-1 font-semibold">{{ $payment->method ?: '-' }}</div></div></div><div class="rounded-lg bg-slate-50 p-5"><div class="text-sm text-slate-500">Jumlah dibayar</div><div class="mt-1 text-3xl font-bold text-teal-800">RM {{ number_format($payment->amount, 2) }}</div></div>@if ($payment->receipt?->status === 'CANCELLED')<div class="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><strong>Resit dibatalkan.</strong> {{ $payment->receipt->cancellation_reason }}</div>@endif<div class="flex justify-between border-t border-slate-200 pt-5"><a href="{{ route('payments.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Kembali</a><button onclick="window.print()" class="rounded-lg bg-teal-700 px-4 py-2 text-sm font-semibold text-white hover:bg-teal-800">Cetak resit</button></div></div>
        </div>
    </div></div>
</x-app-layout>
